package com.edugest.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GradesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradesAllPropertiesEquals(Grades expected, Grades actual) {
        assertGradesAutoGeneratedPropertiesEquals(expected, actual);
        assertGradesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradesAllUpdatablePropertiesEquals(Grades expected, Grades actual) {
        assertGradesUpdatableFieldsEquals(expected, actual);
        assertGradesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradesAutoGeneratedPropertiesEquals(Grades expected, Grades actual) {
        assertThat(actual)
            .as("Verify Grades auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradesUpdatableFieldsEquals(Grades expected, Grades actual) {
        assertThat(actual)
            .as("Verify Grades relevant properties")
            .satisfies(a -> assertThat(a.getGrade()).as("check grade").isEqualTo(expected.getGrade()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradesUpdatableRelationshipsEquals(Grades expected, Grades actual) {
        assertThat(actual)
            .as("Verify Grades relationships")
            .satisfies(a -> assertThat(a.getStudent()).as("check student").isEqualTo(expected.getStudent()))
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()));
    }
}
